drop table if exists doctor CASCADE;
drop table if exists patient CASCADE;
create table doctor
(
    id         bigint generated by default as identity,
    birth_day  timestamp,
    first_name varchar(255),
    last_name  varchar(255),
    patronymic varchar(255),
    phone      varchar(255),
    position   varchar(255),
    primary key (id)
);
create table patient
(
    id         bigint generated by default as identity,
    birth_day  timestamp,
    first_name varchar(255),
    last_name  varchar(255),
    patronymic varchar(255),
    phone      varchar(255),
    doctor_id  bigint,
    primary key (id)
);
alter table patient
    add constraint FKmer5utvy1hiff7ovs6f4bjtnw foreign key (doctor_id) references doctor;